name: "Let's TVC!"

on:
  workflow_dispatch:
  schedule:
    - cron: '0,30 * * * *'
    
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  tvc-full:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Download and prepare Namira-core
        run: |
          # Find the URL for the correct asset (the .tar.gz file) from the latest release
          ASSET_URL=$(curl -s "https://api.github.com/repos/NamiraNet/namira-core/releases/latest" | grep "browser_download_url.*linux_amd64.tar.gz" | cut -d '"' -f 4)

          if [ -z "$ASSET_URL" ]; then
            echo "Error: Could not automatically find the latest Namira-core release URL."
            echo "Attempting to download fallback version v1.1.0."
            # Correct fallback URL to the .tar.gz file
            ASSET_URL="https://github.com/NamiraNet/namira-core/releases/download/v1.1.0/namira-core_1.1.0_linux_amd64.tar.gz"
          fi

          echo "Downloading Namira-core archive from $ASSET_URL"
          # Download the tar.gz archive
          curl -L -o namira-core.tar.gz "$ASSET_URL"

          # Extract the binary from the archive
          echo "Extracting binary..."
          tar -xzf namira-core.tar.gz namira-core

          # Rename the extracted binary to match the name expected by the PHP script
          mv namira-core namira-core-linux-amd64

          chmod +x namira-core-linux-amd64

          echo "Verifying Namira-core version:"
          ./namira-core-linux-amd64 --version
          
      - name: Execute PHP script
        run: |
          php get.php
          php config-test.php
          php duplicate.php
          php toSingbox.php
          php toClashSurfboard.php
          php get_wireguard.php
          php wireguard-toSingbox.php
          php hiddifyWarp.php
          git config --global user.email "thepacketcipher@gmail.com"
          git config --global user.name "thepacketcipher"
          git config credential.helper store
          git add -A
          git commit -m "🚀 Servers Updated - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S')"
          git push
